version: "3"
services:
    app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      image: "ghazanfarmir/docker-apache:latest"
      ports:
        - "${APP_PORT}:80"
      volumes:
        - ${APP_PATH}:${DOCUMENT_ROOT}
      depends_on:
        - database
    database:
      image: mysql:latest
      container_name: database
      restart: always
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "${DB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
volumes:
    db_data: