version: "3"
services:
    app:
      container_name: laravel_app
      build:
        context: .
        dockerfile: Dockerfile
      image: "ghazanfarmir/docker-apache:latest"
      ports:
        - "9000:80"
      volumes:
        - ./app:/var/www/html
      depends_on:
        - database
    database:
      image: mysql:latest
      container_name: database
      restart: always
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "13306:3306"
      environment:
        - MYSQL_DATABASE=dockerphp
        - MYSQL_ROOT_PASSWORD=dockerphp
volumes:
    db_data: